export type Branch = "CT" | "EE" | "ME" | "AU" | "CE";

export interface Company {
  sl: number;
  name: string;
  branches: Branch[];
  location: string;
  vacancy: string;
  salary: string;
}

export const COMPANIES: Company[] = [
  {
    sl: 1,
    name: "TATA Advanced Systems (Aerospace)",
    branches: ["ME", "EE", "AU"],
    location: "Bangalore",
    vacancy: "Trainee Engineer (Direct)",
    salary: "",
  },
  {
    sl: 2,
    name: "Schneider Electricals",
    branches: ["EE"],
    location: "Bangalore, Chennai",
    vacancy: "Trainee Engineer (Direct / NAPS)",
    salary: "",
  },
  {
    sl: 3,
    name: "STS CLADS",
    branches: ["ME"],
    location: "Abu Dhabi, UAE",
    vacancy: "Trainee Engineer",
    salary: "",
  },
  {
    sl: 4,
    name: "Adani Solar Power",
    branches: ["ME", "EE"],
    location: "Mura Port, Gujarat",
    vacancy: "200 positions",
    salary: "",
  },
  {
    sl: 5,
    name: "Britco & Bridco Pvt Ltd",
    branches: ["EE"],
    location: "All over Kerala",
    vacancy: "50 positions",
    salary: "",
  },
  {
    sl: 6,
    name: "Popular Hyundai",
    branches: ["AU"],
    location: "Kerala",
    vacancy:
      "Sales Consultant, Technician, Chief Technician, Service Advisor, Team Leader, Driver",
    salary: "",
  },
  {
    sl: 7,
    name: "AM Motors",
    branches: ["AU"],
    location: "Kerala",
    vacancy:
      "Service Advisor Trainee, Bodyshop Advisor Trainee, Mechanic Trainee",
    salary: "",
  },
  {
    sl: 8,
    name: "Royal Enfield",
    branches: ["ME", "AU"],
    location: "Chennai",
    vacancy: "Shift In-Charge",
    salary: "₹18,500 – ₹20,2500",
  },
  {
    sl: 9,
    name: "Vikram Solar",
    branches: ["EE", "ME"],
    location: "Chennai",
    vacancy: "Shift In-Charge",
    salary: "₹19,000",
  },
  {
    sl: 10,
    name: "ZF Commercial Vehicle Control Systems",
    branches: ["EE", "ME"],
    location: "Chennai",
    vacancy: "",
    salary: "",
  },
  {
    sl: 11,
    name: "Amphenol Automotive",
    branches: ["ME", "AU"],
    location: "Chennai",
    vacancy: "Jr. Engineer",
    salary: "",
  },
  {
    sl: 12,
    name: "Incolt Infra Engineering Pvt Ltd",
    branches: ["CE"],
    location: "Kerala",
    vacancy: "5+",
    salary: "",
  },
  {
    sl: 13,
    name: "Icher Mobile Technologies Pvt Ltd",
    branches: ["EE"],
    location: "Kottakkal",
    vacancy: "10 positions",
    salary: "",
  },
  {
    sl: 14,
    name: "Tata Motors – Luxon",
    branches: ["AU"],
    location: "All over Kerala",
    vacancy: "10 positions",
    salary: "",
  },
  {
    sl: 15,
    name: "Indus Motors LCV (P) Ltd",
    branches: ["AU"],
    location: "All over Kerala",
    vacancy:
      "CRE Female (4), Accounts Asst (2), Technician Trainees (10), Sr. Technician (5), Service Advisor Trainees (8)",
    salary: "",
  },
  {
    sl: 16,
    name: "KIMS Group of Institutions",
    branches: ["CT"],
    location: "Valanchery",
    vacancy:
      "Telecallers, Office Staff, Faculty – BCA, Dialysis, Medical Imaging, Digital Marketing",
    salary: "",
  },
  {
    sl: 17,
    name: "Artline Constructions",
    branches: ["CE"],
    location: "Malappuram / Kozhikode",
    vacancy: "Trainee Engineers Civil – 2 Nos",
    salary: "",
  },
  {
    sl: 18,
    name: "HL Klemove India Pvt Ltd",
    branches: ["ME", "AU"],
    location: "Chennai",
    vacancy: "",
    salary: "₹17,500",
  },
  {
    sl: 19,
    name: "WIPRO Infrastructure Engineering",
    branches: ["EE", "ME"],
    location: "Chennai",
    vacancy: "",
    salary: "₹18,000",
  },
  {
    sl: 20,
    name: "DAMSURE Expert Build Care LLP",
    branches: ["CE"],
    location: "Malappuram / Kozhikode / Kannur",
    vacancy: "Project Executive Male, Freshers/Up to 1 yr exp",
    salary: "₹12,000 – ₹18,000",
  },
  {
    sl: 21,
    name: "Sysbreeze Technologies Pvt Ltd",
    branches: ["CT"],
    location: "Kerala",
    vacancy:
      "Python Developer, Data Science Intern, MERN Stack Developer (0–1 yr exp)",
    salary: "",
  },
  {
    sl: 22,
    name: "Violin Technologies Pvt Ltd",
    branches: ["EE"],
    location: "Chennai",
    vacancy: "Production Engineer / Trainee Engineer",
    salary: "",
  },
  {
    sl: 23,
    name: "CY Myutes Anand Pvt Ltd",
    branches: ["ME"],
    location: "Chennai",
    vacancy: "Production Engineer / Trainee Engineer",
    salary: "",
  },
  {
    sl: 24,
    name: "Royal Enfield – Mass Wheels Pvt Ltd",
    branches: ["AU"],
    location: "Malappuram",
    vacancy:
      "Technician Trainee (Valanchery 2, Edappal 6), Technician (Edappal 3, Vannery 2), Sales Executive, Service Marketing, Accounts, Team Leader",
    salary: "",
  },
  {
    sl: 25,
    name: "Popular Vehicles and Services Ltd",
    branches: ["AU"],
    location: "All over Kerala",
    vacancy: "Service Advisor, Mechanic (ITI), Service Engineer (B.Tech)",
    salary: "",
  },
  {
    sl: 26,
    name: "AVT Natural Products Ltd",
    branches: ["ME", "EE"],
    location: "Ernakulam",
    vacancy:
      "Machine Operation Trainees – Fitter, Mechanical, Machinist; Electronics background also considered",
    salary: "",
  },
  {
    sl: 27,
    name: "HiLITE Group",
    branches: ["CE"],
    location: "Kozhikode",
    vacancy: "10 positions",
    salary: "",
  },
  {
    sl: 28,
    name: "Phoenix Cars India Pvt Ltd",
    branches: ["AU", "ME"],
    location: "Kerala",
    vacancy:
      "Technician (2 yr exp), Job Controller, Sales Consultant, Service Manager, CRE – Sales & Service (Freshers can apply)",
    salary: "",
  },
  {
    sl: 29,
    name: "Volvo Eicher Commercial Vehicle – PSN Automotive",
    branches: ["AU", "ME"],
    location: "Kerala",
    vacancy: "Service Advisor Trainee, Warranty Trainee, Spare Parts Assistant",
    salary: "",
  },
  {
    sl: 30,
    name: "UNIRIDE Honda",
    branches: ["AU", "ME"],
    location: "Kerala",
    vacancy:
      "Sales Executive, Mechanic, Mechanic Trainee, Spare Parts Trainee, PDI Fitter, Service Advisor, Spare Parts Warranty Asst",
    salary: "",
  },
  {
    sl: 31,
    name: "Autobahn Trucking Corporation Pvt Ltd",
    branches: ["AU", "ME"],
    location: "Kerala",
    vacancy:
      "Graduate Engineer Trainee, Technician Trainee, Parts Trainee, Parts Executive, Service Advisor, Sales Executive",
    salary: "",
  },
  {
    sl: 32,
    name: "Phoenix Cars India – Volkswagen Malappuram",
    branches: ["AU", "ME"],
    location: "Malappuram",
    vacancy:
      "Technician, Service Advisor, Customer Relation Executives, Sales Executives",
    salary: "",
  },
  {
    sl: 33,
    name: "Impex Home Appliances",
    branches: ["EE"],
    location: "All over Kerala",
    vacancy: "15 positions",
    salary: "",
  },
  {
    sl: 34,
    name: "Parisons Group of Companies",
    branches: ["ME", "EE"],
    location: "Kerala",
    vacancy:
      "Electrician (4), Electrical Engineer (1), Supervisor (4), Fitter (3), Machine Operator (6)",
    salary: "",
  },
  {
    sl: 35,
    name: "Softroniics",
    branches: ["CT"],
    location: "Kerala",
    vacancy:
      "UI/UX Designer, Data Analyst, BDO, Career Advisor, Python Developer, Cyber Security Specialist",
    salary: "",
  },
  {
    sl: 36,
    name: "Bridgeon Solutions LLP",
    branches: ["CT"],
    location: "Kerala",
    vacancy: "Placement Coordinator, BDE, Program Coordinator, Video Editor",
    salary: "",
  },
  {
    sl: 37,
    name: "Symega Food Ingredient Ltd",
    branches: ["ME", "EE"],
    location: "Ernakulam",
    vacancy: "Operator – Production",
    salary: "",
  },
  {
    sl: 38,
    name: "Glomith Engineers",
    branches: ["ME"],
    location: "Coimbatore",
    vacancy: "Operator – Production",
    salary: "",
  },
  {
    sl: 39,
    name: "SFO Technologies",
    branches: ["EE"],
    location: "Ernakulam",
    vacancy: "",
    salary: "",
  },
  {
    sl: 40,
    name: "MYG",
    branches: ["EE", "ME"],
    location: "Kerala",
    vacancy: "Trainee Engineer / Service Technician",
    salary: "",
  },
  {
    sl: 41,
    name: "Losange Technologies",
    branches: ["CT"],
    location: "Thrissur",
    vacancy:
      "UI/UX Designer, Data Analyst, BDO, Career Advisor, Python Developer, Cyber Security Specialist",
    salary: "",
  },
  {
    sl: 42,
    name: "Coremicron Enterprises LLP",
    branches: ["CT"],
    location: "Malappuram",
    vacancy:
      "Arduino Programmer, Python Developer, Flutter Trainee (1 vacancy) – BSc/BCA/BTech/Diploma",
    salary: "",
  },
  {
    sl: 43,
    name: "AY Tech",
    branches: ["CT"],
    location: "Ernakulam / Thiruvananthapuram",
    vacancy:
      "Jr. Software Engineer (4), Business Development Executive – 0-2 yrs (3), Full Stack Developer – 2 yrs (4)",
    salary: "",
  },
  {
    sl: 44,
    name: "Frametech Steel Structures Pvt Ltd",
    branches: ["CE"],
    location: "Malappuram",
    vacancy: "Site Engineer (2), Draughtsman (2)",
    salary: "",
  },
  {
    sl: 45,
    name: "Asty Constructions LLP",
    branches: ["CE"],
    location: "Kerala",
    vacancy: "Site Engineer, Site Supervisor",
    salary: "",
  },
  {
    sl: 46,
    name: "HK School Trenz",
    branches: ["CT"],
    location: "Kerala",
    vacancy: "Trainee Engineer, Jr. Software Engineer (1)",
    salary: "",
  },
  {
    sl: 47,
    name: "Acmmo Architects",
    branches: ["CE"],
    location: "Kerala",
    vacancy: "Site Supervisor, CAD Designer",
    salary: "",
  },
  {
    sl: 48,
    name: "Eminent Builders & Interiors",
    branches: ["CE"],
    location: "Kerala",
    vacancy: "Site Engineer, Quantity Surveyor",
    salary: "",
  },
  {
    sl: 49,
    name: "Refos Energy Pvt Ltd",
    branches: ["EE"],
    location: "Kozhikode",
    vacancy: "Sales Manager",
    salary: "",
  },
  {
    sl: 50,
    name: "Data Cube Software",
    branches: ["CT"],
    location: "Perinthalmanna",
    vacancy: "PHP Developer, .NET Developer, Scrum Master",
    salary: "",
  },
  {
    sl: 51,
    name: "Regional Technology",
    branches: ["CT"],
    location: "Kozhikode",
    vacancy: "Junior Software Developer",
    salary: "",
  },
  {
    sl: 52,
    name: "RISS Technologies",
    branches: ["CT"],
    location: "Kozhikode",
    vacancy: "Junior Software Developer",
    salary: "",
  },
  {
    sl: 53,
    name: "AN Technologies",
    branches: ["EE"],
    location: "Kerala",
    vacancy: "",
    salary: "",
  },
  {
    sl: 54,
    name: "Avon Engineering",
    branches: ["ME"],
    location: "Mysore",
    vacancy: "Production Operator",
    salary: "",
  },
  {
    sl: 55,
    name: "AJ Engineering",
    branches: ["ME", "AU"],
    location: "Mysore",
    vacancy: "Production Operator",
    salary: "",
  },
  {
    sl: 56,
    name: "KM Tractors",
    branches: ["ME", "AU"],
    location: "Kerala",
    vacancy: "Service Engineer",
    salary: "",
  },
  {
    sl: 57,
    name: "CODE Developers",
    branches: ["CE"],
    location: "Kerala",
    vacancy: "4 Site Engineers",
    salary: "",
  },
];

export const BRANCH_MAP: Record<string, string> = {
  CT: "Computer",
  CE: "Civil",
  EE: "Electrical & Eletronics",
  ME: "Mechanical",
  AU: "Automobile",
};

export const BRANCH_CODES = Array.from(
  new Set(COMPANIES.flatMap((c) => c.branches)),
).sort();

export const QUOTES = [
  "Your Career Begins Here",
  "Opportunity Meets Preparation",
  "Build Your Future, One Step at a Time",
  "Dream Big. Start Here.",
  "Every Expert Was Once a Beginner",
];

export const BRANCH_COLORS: Record<Branch, string> = {
  ME: "bg-blue-50 text-blue-700 border-blue-200 dark:bg-blue-950 dark:text-blue-300 dark:border-blue-800",
  EE: "bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950 dark:text-amber-300 dark:border-amber-800",
  AU: "bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950 dark:text-emerald-300 dark:border-emerald-800",
  CE: "bg-orange-50 text-orange-700 border-orange-200 dark:bg-orange-950 dark:text-orange-300 dark:border-orange-800",
  CT: "bg-sky-50 text-sky-700 border-sky-200 dark:bg-sky-950 dark:text-sky-300 dark:border-sky-800",
};
